### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Evanfor1990** [lisen87/image_pickers#155]
com.leeson.image_pickers.activitys.PhotosActivity}: android.util.AndroidRuntimeException: requestFeature() must be called before adding content

**Comment by qilong-io** [comment]
我遇到了同样的问题，请问怎么处理呢？

**Comment by qilong-io** [comment]
E/AndroidRuntime(25184): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.junlang.mespad/com.leeson.image_pickers.activitys.PhotosActivity}: android.util.AndroidRuntimeException: requestFeature() must be called before adding content
E/AndroidRuntime(25184): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4626)
E/AndroidRuntime(25184): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4822)
E/AndroidRuntime(25184): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:118)
E/AndroidRuntime(25184): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:153)
E/AndroidRuntime(25184): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:104)
E/AndroidRuntime(25184): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:3078)
E/AndroidRuntime(25184): 	at android.os.Handler.dispatchMessage(Handler.java:117)
E/AndroidRuntime(25184): 	at android.os.Looper.loopOnce(Looper.java:210)
E/AndroidRuntime(25184): 	at android.os.Looper.loop(Looper.java:302)
E/AndroidRuntime(25184): 	at android.app.ActivityThread.main(ActivityThread.java:9668)
E/AndroidRuntime(25184): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25184): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:601)
E/AndroidRuntime(25184): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1062)
E/AndroidRuntime(25184): Caused by: android.util.AndroidRuntimeException: requestFeature() must be called before adding content
E/AndroidRuntime(25184): 	at com.android.internal.policy.PhoneWindow.requestFeature(PhoneWindow.java:521)
E/AndroidRuntime(25184): 	at android.app.Activity.requestWindowFeature(Activity.java:5513)
E/AndroidRuntime(25184): 	at com.leeson.image_pickers.activitys.PhotosActivity.onCreate(PhotosActivity.java:351)
E/AndroidRuntime(25184): 	at android.app.Activity.performCreate(Activity.java:9037)
E/AndroidRuntime(25184): 	at android.app.Activity.performCreate(Activity.java:8996)
E/AndroidRuntime(25184): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1470)
E/AndroidRuntime(25184): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4608)

**Comment by qilong-io** [comment]
![Image](https://github.com/user-attachments/assets/f577691e-c316-400e-995f-15be61049bd1)

**Comment by lisen87** [comment]
已修改 image_pickers: ^2.0.6
