### ISSUE TITLE
saveByteDataImageToGallery报错

### ISSUE THREAD

**Issue by JeffYi2017** [lisen87/image_pickers#29]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.hasAlpha()' on a null object reference
E/AndroidRuntime(10332): 	at com.leeson.image_pickers.utils.Saver$7.run(Saver.java:384)
E/AndroidRuntime(10332): 	at java.lang.Thread.run(Thread.java:761)

**Comment by lisen87** [comment]
手机安卓系统版本是多少？什么型号手机？

**Comment by JeffYi2017** [comment]
> 手机安卓系统版本是多少？什么型号手机？

我试了两个手机android6.0,7.0的都报错，vivo，还有杂牌机，我调试Uint8List是有值的

**Comment by JeffYi2017** [comment]
搜索了下会不会是这个原因
BitmapFactory.decodeByteArray函数获取的bitmap为null

BitmapFactory .Options opts = new BitmapFactory.Options();
opts. inJustDecodeBounds = false ;//inJustDecodeBounds 需要设置为false，如果设置为true，那么将返回null
opts. inSampleSize = size ;
bitmap = BitmapFactory. decodeByteArray(byteArray, 0, byteArray.length , opts);

**Comment by lisen87** [comment]
这个值默认应该是false的。可以先改一下源码看看是不是真的是这个情况

**Comment by lisen87** [comment]
@JeffYi2017 发布了新版本了，去掉了bitmap了
